name: build

on:
  push:
    paths:
      - '**'
  workflow_dispatch:

jobs:
  build-msvc:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: recursive
      
      - name: Pull Latest MSVC
        uses: TheMrMilchmann/setup-msvc-dev@v4
        with:
          arch: x86

      - name: Build using CMake
        run: |
          cmake -S . -B build -G "Visual Studio 17 2022" -A Win32
          cmake --build build --config Release

      - name: Release
        uses: softprops/action-gh-release@v2
        if: github.event_name == 'push'
        env:
          FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
        with:
          working_directory: build/Release
          files: '*.dll'
          generate_release_notes: true
          name: "${{ github.sha }}"
          target_commitish: "${{ github.sha }}"
          tag: "${{ github.sha }}"
          make_latest: true

      - name: Upload Artifact
        uses: actions/upload-artifact@v5
        if: github.event_name == 'workflow_dispatch' || github.event_name == 'repository_dispatch'
        with:
          path: build/Release/*.dll
          name: chuniwide
    
